# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics modules.

Example:
    Visualize a module with Netron.
    ```python
    from ultralytics.nn.modules import *
    import torch
    import os

    x = torch.ones(1, 128, 40, 40)
    m = Conv(128, 128)
    f = f"{m._get_name()}.onnx"
    torch.onnx.export(m, x, f)
    os.system(f"onnxslim {f} {f} && open {f}")  # pip install onnxslim
    ```
"""

from .block import (
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    ELAN1,
    PSA,
    SPP,
    SPPELAN,
    SPPF,
    A2C2f,
    AConv,
    ADown,
    Attention,
    BNContrastiveHead,
    Bottleneck,
    BottleneckCSP,
    C2f,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    CBFuse,
    CBLinear,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepNCSPELAN4,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    TorchVision,
    ASFF2,
    ASFF3,
    ChannelAttention_HSFPN,
    Multiply,
    Add,
    SPPFCSPC,
    DilateBlock,C2f_MultiDilatelocalAttention,
    CSPStage,
    C2f_Faster_EMA,C2f_EMA1,C2f_EMA2,
    BiFormerBlock,
    FocalModulation,
    #C2f_iAFF
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    Index,
    LightConv,
    RepConv,
    SpatialAttention,
    BiFPN_Concat2,
    BiFPN_Concat3,
    AKConv,
    LSKA,SPPF_LSKA,
    SCAM,
    VoVGSCSP,VoVGSCSPC,GSConv
)
from .head import OBB, Classify, Detect, Pose, RTDETRDecoder, Segment, WorldDetect, v10Detect
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)

__all__ = (
    "Conv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "C3k2",
    "SCDown",
    "C2fPSA",
    "C2PSA",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "BottleneckCSP",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "v10Detect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepNCSPELAN4",
    "ADown",
    "SPPELAN",
    "CBFuse",
    "CBLinear",
    "AConv",
    "ELAN1",
    "RepVGGDW",
    "CIB",
    "C2fCIB",
    "Attention",
    "PSA",
    "TorchVision",
    "Index",
    "A2C2f",
    "BiFPN_Concat2",
    "BiFPN_Concat3",
    "ASFF2",
    "ASFF3",
    "ChannelAttention_HSFPN",
    "Multiply",
    "Add",
    "SPPFCSPC",
    "AKConv",
    "EMA",
    "CSPStage",
    "LSKA","SPPF_LSKA",
    "C2f_SCConv",
    "C2f_Faster_EMA","C2f_EMA1","C2f_EMA2",
    "DilateBlock","C2f_MultiDilatelocalAttention",
    "SCAM",
    "VoVGSCSP","VoVGSCSPC","GSConv",
    "BiFormerBlock",
    "DAttentionBaseline",
    "FocalModulation",
    #"C2f_iAFF"

)
from ultralytics.nn.modules.CBAM import CBAM
from ultralytics.nn.modules.EMA import EMA
from ultralytics.nn.modules.SCConv import C2f_SCConv
from ultralytics.nn.modules.ODConv import C2f_ODConv
from ultralytics.nn.modules.CA import CoordAtt
from ultralytics.nn.modules.GAM import GAM
from ultralytics.nn.modules.DAT import DAttentionBaseline
